exclude: '^(docs/)|(tests)'
repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.26.0
  hooks:
  - id: yapf
    language: system

- repo: git://github.com/PyCQA/prospector
  rev: 1.1.6.2
  hooks:
  - id: prospector
    language: system

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: local
  hooks:
  - id: travis-linter
    name: travis
    entry: travis lint
    files: .travis.yml
    language: ruby
    additional_dependencies: ['travis']
  - id: version-updater
    name: version
    language: system
    entry: python ops/update_version.py
    always_run: true
