doc-warnings: true

ignore-paths:
    - docs
    - examples
    - tests

pylint:
    max-line-length: 140

pyflakes:
  run: false

pep257:
  run: true
  disable:
    - D104
    - D105
    - D107
    - D202
    - D203
    - D204
    - D212
    - D406
    - D407
    - D412
    - D413
    - D416
    - D415
