notifacation:
  email: false
language: python
dist: thrusty
python:
  - 3.6
  - 3.7
cache: pip
install:
  - pip install --upgrade pip setuptools
  - pip install numpy
  - pip install Cython
  - pip install .[dev]
  - pip install tox-travis coveralls
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="unittests" TOX_ENV=t4me
script: ./run_ci_tests.sh
#after_success:
#  - coverage combine
#  - coveralls
