# Copyright 2016 Espen Flage-Larsen
#
#    This file is part of T4ME and covered by the BSD 3-clause license.
#
#    You should have received a copy of the BSD 3-clause license
#    along with T4ME.  If not, see <https://opensource.org/licenses/BSD-3-Clause/>.

version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s %(message)s\n"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s\n"

handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    mode: w
    formatter: simple
    filename: output/info.log

loggers:
  tests:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]
